version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    command: uvicorn app.backend.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    env_file:
      - .env

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules  # Volumen anónimo para node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    environment:
      - VITE_API_URL=http://backend:${BACKEND_PORT}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: